---
title: "Fitting a von Bertalanffy Growth Function"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot[RO,RE]{Ogle (AFS Kansas City, 20 Aug 2016)}
- \fancyfoot[LE,LO]{Fitting a von Bertalanffy Growth Function}
output: pdf_document
geometry: left=0.5in, right=0.5in, top=0.5in, bottom=0.75in
---

```{r echo=FALSE, results='hide'}
source("../knitr_setup.R")
```

# Preliminaries
\vspace{-12pt}
```{r results='hide', warning=FALSE, message=FALSE}
library(FSAdata)           # for TroutBR data
library(FSA)               # for filterD(), headtail(), col2rgbt(), vbFuns(), vbStart()
library(nlstools)          # for nlsBoot()
```

\vspace{-12pt}
# Loading the Data and Some Preparations
\vspace{-12pt}
```{r message=FALSE}
data(TroutBR)
str(TroutBR)
rbt <- filterD(TroutBR,species=="Rainbow")
headtail(rbt)
```

```{r}
xlbl <- "Age (yrs)"
ylbl <- "Total Length (in)"
clr <- col2rgbt("black",1/20)
```

\vspace{-12pt}
# Examine Plot of Data
\vspace{-12pt}
```{r}
plot(tl~age,data=rbt,pch=19,col=clr,xlab=xlbl,ylab=ylbl)
```

# Fit Typical VBGF
\vspace{-12pt}
## Declare a Function
\vspace{-12pt}
```{r}
vb <- vbFuns("Typical",msg=TRUE)
vb
## Next two simply demonstrate how this function works
vb(8,Linf=300,K=0.3,t0=-1)
vb(1:8,c(300,0.3,-1))
```

## Find Starting Values
\vspace{-12pt}
```{r fig.show='hold'}
# Demos manual generation with plot ... LEFT plot
svb <- vbStarts(tl~age,data=rbt,type="Typical",plot=TRUE,
                fixed=list(Linf=30,K=0.3,t0=0))
# Demos automatic generation ... RIGHT plot
svb <- vbStarts(tl~age,data=rbt,type="Typical",plot=TRUE)
```

\newpage
## Check Assumptions
```{r warning=FALSE, fig.width=6}
fit1 <- nls(tl~vb(age,Linf,K,t0),data=rbt,start=svb)
residPlot(fit1)
```

## Summarize the Model Fit
```{r message=FALSE}
summary(fit1,correlation=TRUE)
( cf <- coef(fit1) )
confint(fit1)
```

```{r fig.width=7,fig.height=3,fig.show='hold'}
boot1 <- nlsBoot(fit1,niter=1000)
str(boot1)
headtail(boot1$coefboot)
confint(boot1,plot=TRUE,rows=1,cols=3)
```

\newpage
## Make Predictions
```{r}
ageX <- 8
predict(fit1,data.frame(age=ageX))
pv <- apply(boot1$coefboot,MARGIN=1,FUN=vb,t=ageX)
quantile(pv,c(0.025,0.975))
```

## Visualize the Fit
```{r par1=TRUE, fig.show='hold'}
plot(tl~age,data=rbt,xlab=xlbl,ylab=ylbl,pch=19,col=clr)
curve(vb(x,cf),from=3,to=10,n=500,lwd=2,col="red",add=TRUE)
```

```{r echo=FALSE, results="hide", message=FALSE}
purl2("Growth_Single.Rmd",moreItems="knitr",out.dir="../scripts",topnotes="AFS Kansas City 20-Aug-16")
```
