---
title: "Comparing Age Assignments Exercise"
author: "Derek H. Ogle, Northland College"
date: "20-Aug-2016"
output: pdf_document
---

[Herbst and Marsden (2011)](http://www.uvm.edu/rsenr/emarsden/documents/Herbst%20and%20Marsden%20whitefish%20age%20structure%20comparison.pdf) compared the precision, bias, and reader uncertainty of ages estimated from the scales, dorsal fin rays, and otoliths of 151 [Lake Whitefish](https://en.wikipedia.org/wiki/Lake_whitefish) (*Coregonus clupeaformis*) captured from [Lake Champlain](https://en.wikipedia.org/wiki/Lake_Champlain) in 2009.  The inital age estimates from two readers and a consensus age between the two readers from each of the three structures (variables are the structure name with a "1" or "2" appended to denote the reader or "C" for the consensus age) may be obtained with `data(WhitefishLC)` from the `FSAdata` package.  Use these data to answer the questions below.

1. Use tabular, graphical, and statistical methods to describe any apparent bias in age estimates from otoliths between the two readers.
1. Describe precision in age estimates between the two readers for otoliths.
\vspace{24pt}
1. Describe any apparent bias between the *consensus* age estimates from otoliths and scales.
\vspace{24pt}
1. [*Time Permitting*] Use tabular, graphical, and statistical methods to describe any apparent bias in age estimates from scales between the two readers.
1. [*Time Permitting*] Describe precision in age estimates between the two readers for scales.
1. [*Time Permitting*] Describe any apparent bias in consensus age estimates from scales and fin rays.
