---
title: "ALK Construction Exercise"
author: "Derek H. Ogle, Northland College"
date: "20-Aug-2016"
output: pdf_document
---

[Wolfert (1980)](https://pubs.er.usgs.gov/publication/1000461) measured the total length (TL) of 1288 [Rock Bass](https://en.wikipedia.org/wiki/Rock_bass) (*Ambloplites rupestris*) from Eastern [Lake Ontario](https://en.wikipedia.org/wiki/Lake_Ontario) in the late 1970s.  In addition, [scales](https://en.wikipedia.org/wiki/Fish_scale) were removed for age estimation from as many as 10 specimens from each 10 mm length interval.  All data can be obtained from `data(RockBassLO2)` from the `FSAdata` package. [*Note that the filename contains an "oh" not a "zero."*].

1. Separate the observed data into age- and length-samples.
    a. How many fish are in each sample?
1. Add a variable to the age-sample that contains the 10 mm TL categories.  Construct a table of the **number** (not proportion) of fish in each age and 10 mm TL category in the age-sample.  From these results, compute each of the following *by hand* (i.e., not using R).
    a. How many Rock Bass in the age-sample are in the 180 mm TL category?
    a. How many age-7 Rock Bass are in the age-sample?
    a. What proportion of Rock Bass in the 210 mm TL category are age 4?
    a. What proportion of Rock Bass in the 180 mm TL category are age 8?
1. Construct an **observed** age-length key from the table above (using R).  From these results answer the following questions.
    a. What proportion of Rock Bass in the 210 mm TL category should be assigned age 5?
    a. How many of thirty Rock Bass in the 180 mm TL category should be assigned age 5?
    a. Construct a plot of the **observed** age-length key.  Are there any potential anomalies in the plot that would suggest that a smoothed age-length key should be used instead?
1. Construct a **smoothed** age-length key.  From these results answer the following questions.
    a. What proportion of Rock Bass in the 210 mm length category should be assigned age 5?
    a. How many of thirty Rock Bass in the 180 mm length category should be assigned age 5?
1. **Make sure to save a cleaned (no code that is not needed or results in an error) script!**
