---
title: "ALK Application Exercise"
author: "Derek H. Ogle, Northland College"
date: "20-Aug-2016"
output: pdf_document
---

Continue with the data.frames and age-length keys constructed in the previous exercise.  You may either extend your previous script or create a new script that `source()`s the previous script.

1. Use the semi-random age assignment technique from Isermann and Knight (2005) and the **observed** age-length key to assign ages to the unaged fish in the length-sample.  Combine the age-sample and the age-assigned length-sample into a single data frame, add a variable to this data.frame that contains the 10 mm TL categories, and use the combined data frame to answer the following questions.
    a. How many fish are estimated to be age 5?
    a. How many fish are estimated to be age 11?
    a. Plot the age distribution for all fish.
    a. How many fish are in the 150 mm TL interval?
    a. What is the mean TL of age-5 fish?
    a. Plot the length-at-age with the mean length-at-age superimposed for all fish.
    a. Compare your results from questions a-f to someone else's results (or repeat those questions).  Did you both get the *exact* same results?  Why or why not?  If not, how different were they?
\vspace{24pt}
1. [**Time Permitting**] Repeat the previous question but using the **smoothed** age-length key.