---
title: "Comparing VBGF Exercise"
author: "Derek H. Ogle, Northland College"
date: "20-Aug-2016"
output: pdf_document
---

[Mooij et al. (1999)](http://www.tandfonline.com/doi/abs/10.1577/1548-8659%281999%29128%3C0483%3AAACOFG%3E2.0.CO%3B2) examined length-at-age data of [European Perch](https://en.wikipedia.org/wiki/European_perch) (*Perca fluviatilis*) from [Lake Tjeukemeer](http://wldb.ilec.or.jp/data/databook_html/eur/eur-01.html) (The Netherlands) to identify possible sexual dimorphism in growth trajectories.  Their data consisted of fork length (FL; cm), ages (yrs) from otoliths, and sex from 69 fish and may be obtained with `data(EuroPerchTJ)` from the `FSAdata` package).  Use these data to answer the following questions.

1. Plot FL versus age with different symbols for each sex.
    a. Do you foresee any model fitting problems with these data?
    a. Do you observe any possible differences in growth between the sexes?
1. Fit the *additive* errors (i.e., no logarithms) typical VBGF where all parameters differ by sex.
    a. Assess the assumptions from this model fit.
    a. Compute point and bootstrapped 95% confidence interval estimates for each parameter in this model.  Describe any problems that you encountered.
1. Find the most parsimonius model that is a subset of the model fit above.
    a. Using either a likelihood ratio or extra sums-of-squares test.
    a. Summarize (in words) the results of the most parsimonious model identified above.
\vspace{24pt}
1. [**Time Permitting**] Fit the typical VBGF seperately to both sexes.
    a. Compute point and bootstrapped 95% confidence interval estimates for each parameter in the separate models.
    a. Describe any problems that you encountered.
    a. How do the point estimates from these separate models compare to the point estimates from the most complex model in #2 above?
    a. Do you see any issues with the confidence intervals?  If so, describe.
1. [**Time Permitting**] Construct a summary graphic that shows the growth trajectories superimposed on the observed data for both sexes.
